name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker images
      run: docker-compose build
    
    - name: Test containers can start
      run: |
        docker-compose up -d
        sleep 30
        docker-compose ps
        docker-compose down
    
    - name: Tag images with timestamp
      run: |
        TIMESTAMP=$(date +%s)
        docker tag $(docker-compose images -q backend) sent-clf-realtime-backend:$TIMESTAMP
        docker tag $(docker-compose images -q frontend) sent-clf-realtime-frontend:$TIMESTAMP
        echo "Images tagged with timestamp: $TIMESTAMP"
